IF DB_ID('SuperBowlOps') IS NOT NULL
BEGIN
    ALTER DATABASE SuperBowlOps SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SuperBowlOps;
END
GO

CREATE DATABASE SuperBowlOps;
GO

USE SuperBowlOps;
GO
